# Generated by Django 2.2.6 on 2020-12-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20201224_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Выражайтесь на здоровье!/n P.S. Без мата', verbose_name='Текст'),
        ),
    ]
